### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by adrien2p**
Add some starters

### CODE REVIEW

**Comment by adrien2p** [comment]
Some news ?

**Comment by kamilmysliwiec** [comment]
The readme structure changed a little since v4, so pr is obsolete now :disappointed: Thanks man!!

**Comment by adrien2p** [comment]
i'll update all repo based on nest and after that would you like put the links some where or not ?

**Comment by kamilmysliwiec** [comment]
I think I'll create a page in the official docs for these links in the futuer ;)

**Pull request closed without merging**
