### PR TITLE
feat(hooks): async onModuleInit, #86

### PR DESCRIPTION
**Pull request by cojack**
I have changed the behaviour of the `callInitHook` to be called right into after they are initialized, before anything else, so they are called before:

- socket
- middleware
- microservices
- routes

and they are async. What I also figured out, each `Component` can have as well this metod and they will be called as well.

FE:
**SomeModule.ts**
```typescript
@Module({
	components: [SomeService]
})
export class SomeModule implements OnModuleInit {
	constructor(private someService: SomeService) {}

	async onModuleInit(): Promise<any> {
		return this.someService.connect();
	}
}
```
**SomeService.ts**
```typescript
@Component()
export class SomeService {
	connect() {
		return Promise.all([
			this.connectSomeRDBMS(),
			this.connectSomeNOSQL()
		]);
	}
}
```

Server will wait until this promise will be resolved.

Please test it and blame it! :smiley: 

Regards.

### CODE REVIEW

**Comment by cojack** [comment]
@kamilmysliwiec could you help with CI? Its failing over and over :cry:

**Comment by ThomRick** [comment]
Hey @cojack !
Do the tests run in local environment ?

**Comment by cojack** [comment]
@ThomRick first PR #111 should be merged, then this will work (because of typescript 2.4)

**Comment by kamilmysliwiec** [comment]
v4 provides the async components feature, which should fit your requirements http://www.docs.nestjs.com/advanced/async-components :)

**Pull request closed without merging**
